### ISSUE TITLE
I dont have enough money

### ISSUE THREAD

**Issue by RetroRadical** [mb243/THBL-issues#2]
I retroradical do not have enough money for my expensive lifestyle.... what do?

**Comment by mb243** [comment]
Perhaps sell things to the shop?

**Comment by Acheron4171** [comment]
Perhaps change your lifestyle?

**Comment by RetroRadical** [comment]
What would donald trump do in such a dilemma?

**Comment by Acheron4171** [comment]
Become president and ruin the country getting more money for himself.

**Comment by RetroRadical** [comment]
*googles how to become president of THBL*

**Comment by Acheron4171** [comment]
Google: _assassinate the current president._
